name: Deploy

on:
  schedule:
    - cron: '5 */12 * * *' # 5分と、12時間ごとに実行
  workflow_dispatch:

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
